[project]
name = "latest"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "databases>=0.9.0",
    "fastapi>=0.115.14",
    "python-decouple>=3.8",
    "sqlalchemy>=2.0.41",
]
